### PR TITLE
add new Mensa Filmuniversität

### PR DESCRIPTION
**Pull request by SusanneBue**
a new canteen openend recently in the Filmuniversität

### CODE REVIEW

**Comment by f4lco** [comment]
Thank you very much! That looks very good.
I'm curious, let me ask:
- did you find the [docs](https://om-parser-stw-potsdam-v2.readthedocs.io/en/latest/)? Did you find that helpful / what was your ramp-up experience like?
- Which client / app do you use?  It's been a while since I have last been to uni.

For the PR: I'll merge it as-is and then ping the guy who deploys it 👍 You may expect a couple more notifications from GitHub.

🚀

**Comment by SusanneBue** [comment]
Sorry for the late response, seems like I missed your comment...

I did not have a deeper look into the docs, I just skimmed the code. Compliments to your structure that adding a new mensa just required editing a config file :D Running the project locally worked smoothly.
I consume the openmensa API to post the daily menu to a slack channel.

Can I somehow support in registering the new canteen? It does not yet show up or am i missing something?

**Comment by f4lco** [comment]
Thank you for the kind words and sorry for the long delay, busy times.

I can confirm the canteen is not on OpenMensa, but the parser works and shows that the mensa has actually a menu with meals  🤷‍♂️  (last time I checked I believe they were closed or something).

So let's ping @kaifabian, he's doing the operations. @kaifabian is there any piece missing, like some sort of registration on the OpenMensa platform? Filmuniversität ain't showing up. Thanks for checking.

**Comment by kaifabian** [comment]
Sorry for the delay, debugging this took a bit longer than expected. Long story short: I updated the Linux kernel and libc on the host running the parser, but didn't update the Docker runtime. Thus it used an outdated libseccomp (or profile or whatever= that had issues with the "new" `faccessat2` syscall (making that syscall return `-EPERM`).

Also, Docker thankfully kept the old image running (great, so that other canteens are still available on OpenMensa), but the failure emails didn't leave the send queue...

I've updated the necessary packages and with the next deployment run, the new canteen should reach production.

**Comment by kaifabian** [comment]
Ugh. New deployment is failing with:

```
Traceback (most recent call last):
  File "/opt/om-parser-stw-potsdam-v2/./stw_potsdam/views.py", line 6, in <module>
    import cachetools as ct
ModuleNotFoundError: No module named 'cachetools'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
```

@f4lco any idea what might cause this? If I run a `pipenv run python` and `import cachetools` in the container, everything looks alright.

**Comment by f4lco** [comment]
> If I run a pipenv run python and import cachetools in the container, everything looks alright.

@kaifabian That really odd. I've got no idea and no real starting point, because I lack a reproducer. I tried successfully:

```
$ docker build .
$ docker run -p 3080:3080 475 # image id
$ http :3080
$ http :3080/canteens/filmuniversitaet/meta
$ http :3080/canteens/filmuniversitaet/menu
```

🤷  It must be some type of environment issue. Other random issues on GH bring up that cachetools dropped Python 2 support at some point. Are you sure the interpreter is not Python 2? I got a slightly different import-related error when I try `python2 -m stw_potsdam.views` on my machine.

**Comment by f4lco** [comment]
@kaifabian I don't think Filmuniversität is showing up on the map https://openmensa.org/#14/52.3879/13.1263. Do you think there is still anything wrong with it?

**Comment by kaifabian** [comment]
Interesting. It is definitely synced to OpenMensa (ref. https://openmensa.org/c/1222), but for some reason it's missing geo data and I'm not allowed to change it. Investigating.

**Comment by kaifabian** [comment]
Should be fixed now.

**Comment by f4lco** [comment]
Thank you very much! 💯 
And thanks @SusanneBue for bearing with us.

**Pull request merged**
